### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by iTzAndrew33212** [fernanACM/BetterItemID#1]
Hi There, would it be possible to show the number id of the block, instead of the name?

Thanks
Andrew

**Comment by fernanACM** [comment]
> Hi There, would it be possible to show the number id of the block, instead of the name?
> 
> Thanks
> Andrew 

Due to the API change, now I put it works with id in letters, the numerical id is no longer possible to display it exactly. because of the change

**Comment by iTzAndrew33212** [comment]
I see, thank you for getting back to me 👌

**Comment by iTzAndrew33212** [comment]
I see, thank you for getting back to me 👌
